type NameCard {
	_id: ObjectID!
	name: String!
	email: String
	phone: String
	gender: Gender
	remarks: String
	status: AccountStatus!
	lupdBy: String
	lupdDttm: Time!
}

input NewNameCard {
	name: String!
	email: String
	phone: String
	gender: Gender
}

input UpdateNameCard {
	remarks: String
	status: AccountStatus!
}