

type Worship {
	worshipId: String!
	title: String!
	type: String!
	messenger: String!
	note: String, 
	verse: String, 
	link: String, 
	docs: [WorshipDoc!]!
}

type WorshipDoc {
	title: String
	link: String
	type: String
}

input NewWorship {
	worshipId: String!
	title: String!
	type: String!
	messenger: String!
	note: String
	verse: String 
	link: String 
}

input NewWorshipDoc {
	title: String
	type: String
	link: String 
}